# Generated by Django 5.1 on 2024-08-29 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objectives', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectives',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
